### ISSUE TITLE
Umlaute not working in passwords for mail accounts

### ISSUE THREAD

**Issue by Samurai1201** [bandundu/email-archiver#3]
Got this error while adding a mail account:

```
web-1  | Traceback (most recent call last):
web-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1488, in __call__
web-1  |     return self.wsgi_app(environ, start_response)
web-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1466, in wsgi_app
web-1  |     response = self.handle_exception(e)
web-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
web-1  |     response = self.full_dispatch_request()
web-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
web-1  |     rv = self.handle_user_exception(e)
web-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
web-1  |     rv = self.dispatch_request()
web-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
web-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
web-1  |   File "/app/app.py", line 58, in create_account
web-1  |     email_archiver.create_account(conn, email, password, protocol, server, port)
web-1  |   File "/app/email_archiver.py", line 257, in create_account
web-1  |     client.login(email, password)
web-1  |   File "/usr/local/lib/python3.9/imaplib.py", line 610, in login
web-1  |     typ, dat = self._simple_command('LOGIN', user, self._quote(password))
web-1  |   File "/usr/local/lib/python3.9/imaplib.py", line 1230, in _simple_command
web-1  |     return self._command_complete(name, self._command(name, *args))
web-1  |   File "/usr/local/lib/python3.9/imaplib.py", line 987, in _command
web-1  |     arg = bytes(arg, self._encoding)
web-1  | UnicodeEncodeError: 'ascii' codec can't encode character '\xdc' in position 10: ordinal not in range(128)
```

The mail Account password cotains an Ü

**Comment by bandundu** [comment]
Hi @Samurai1201 this should be fixed in https://github.com/bandundu/email-archiver/commit/394a9825dc389730bd3d94bc6f7217c5f4d0690b

can you please do a docker-compose pull, retry and let me know?

**Comment by Samurai1201** [comment]
Thanks for the quick response :)

I tried the docker compose pull as you suggested and even built the image from source, but the container doesnt even start now.
It exits with code 0, without even writing anything to log.

**Comment by bandundu** [comment]
Can you provide info on the architecture you are using? I currently have no ARM machine available, so can not test for that. Also, can you give me steps you did, so I can reproduce

**Comment by Samurai1201** [comment]
It starts now as before, but I still get the same error message

```
web-1  | Traceback (most recent call last):
web-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1488, in __call__
web-1  |     return self.wsgi_app(environ, start_response)
web-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1466, in wsgi_app
web-1  |     response = self.handle_exception(e)
web-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
web-1  |     response = self.full_dispatch_request()
web-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
web-1  |     rv = self.handle_user_exception(e)
web-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
web-1  |     rv = self.dispatch_request()
web-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
web-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
web-1  |   File "/app/app.py", line 58, in create_account
web-1  |     email_archiver.create_account(conn, email, password, protocol, server, port)
web-1  |   File "/app/email_archiver.py", line 260, in create_account
web-1  |     client.login(email, password_bytes.decode('utf-8'))  # Decode the bytes back to a string
web-1  |   File "/usr/local/lib/python3.9/imaplib.py", line 610, in login
web-1  |     typ, dat = self._simple_command('LOGIN', user, self._quote(password))
web-1  |   File "/usr/local/lib/python3.9/imaplib.py", line 1230, in _simple_command
web-1  |     return self._command_complete(name, self._command(name, *args))
web-1  |   File "/usr/local/lib/python3.9/imaplib.py", line 987, in _command
web-1  |     arg = bytes(arg, self._encoding)
web-1  | UnicodeEncodeError: 'ascii' codec can't encode character '\xdc' in position 8: ordinal not in range(128)
```

**Comment by Samurai1201** [comment]
I was successful at adding the account :)
Unfortunately briefbox was unable to archive any emails with error:
```
web-1  | 2024-03-12 09:40:57,291 - INFO - Started email archiving for account 2.
web-1  | 2024-03-12 09:40:57,368 - ERROR - An error occurred during email archiving for account 2: 'ascii' codec can't encode character '\xdc' in position 8: ordinal not in range(128)
web-1  | 2024-03-12 09:40:57,368 - ERROR - Exception details: Traceback (most recent call last):
web-1  |   File "/app/email_archiver.py", line 104, in fetch_and_archive_emails
web-1  |     client.login(username, password)
web-1  |   File "/usr/local/lib/python3.9/imaplib.py", line 610, in login
web-1  |     typ, dat = self._simple_command('LOGIN', user, self._quote(password))
web-1  |   File "/usr/local/lib/python3.9/imaplib.py", line 1230, in _simple_command
web-1  |     return self._command_complete(name, self._command(name, *args))
web-1  |   File "/usr/local/lib/python3.9/imaplib.py", line 987, in _command
web-1  |     arg = bytes(arg, self._encoding)
web-1  | UnicodeEncodeError: 'ascii' codec can't encode character '\xdc' in position 8: ordinal not in range(128)
```

**Comment by bandundu** [comment]
Wow. My bad I have limited possibility to test. Should now again be hopefully fixed in https://github.com/bandundu/email-archiver/commit/d164620682641e8d8c902e38d94b8bd6b88db53b

Please bare with me ;)

Das bekommen wir schon hin!

**Comment by Samurai1201** [comment]
It now works as expected
Thanks a lot :)

P.S.: Would it be possible to archive whole email accounts? That would be really useful.
        And when Im at it asking for features, an import function for EML generated according to rfc 2822 would be a godsend

**Comment by bandundu** [comment]
@Samurai1201  everything is possible ;). Please create seperate issues for each where you detail out what you need and i will take a look. Glad it works now
